language: node_js
node_js:
  - 10.16.0
cache:
  directories:
    - node_modules
install:
  - npm install
before_script:

script:
  - npm run build

after_script:
  after_script:
    - cd ./dist
    - git init
    - git config user.name "bless-19946"
    - git config user.email "962269059@qq.com"
    - git add .
    - git commit -m "Travis CI Auto Builder"
    - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:deploy

branches:
  only:
    - master
